version: '3.8'

services:
  sys_livros:
    image: store/oracle/database-enterprise:12.2.0.1-slim
    restart: always
    ports: 
      - '1521:1521'
    volumes:
      - sys_livros:/var/lib/oracle/data

volumes:
  sys_livros:
    driver: local