CREATE TABLE ADMIN.AUTOR (
	ID_AUTOR NUMBER DEFAULT "ADMIN"."ISEQ$$_80346".nextval,
	NOME VARCHAR2(50),
	NACIONALIDADE VARCHAR2(20),
	ANO_NASCIMENTO NUMBER,
	CONSTRAINT SYS_C0011837 CHECK ("ID_AUTOR" IS NOT NULL),
	CONSTRAINT SYS_C0011838 PRIMARY KEY (ID_AUTOR)
);
CREATE UNIQUE INDEX SYS_C0011838 ON ADMIN.AUTOR (ID_AUTOR);

CREATE TABLE ADMIN.LIVRO (
	ID NUMBER DEFAULT "ADMIN"."ISEQ$$_79883".nextval,
	TITULO VARCHAR2(50),
	ISBN VARCHAR2(20),
	EDICAO NUMBER,
	DESCRICAO VARCHAR2(4000),
	CONSTRAINT SYS_C0011631 CHECK ("ID" IS NOT NULL),
	CONSTRAINT SYS_C0011632 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX SYS_C0011632 ON ADMIN.LIVRO (ID);

CREATE TABLE ADMIN.LIVRO_AUTOR (
	ID_AUTOR NUMBER,
	ID_LIVRO NUMBER,
	CONSTRAINT SYS_C0011863 CHECK ("ID_AUTOR" IS NOT NULL),
	CONSTRAINT SYS_C0011864 CHECK ("ID_LIVRO" IS NOT NULL),
	CONSTRAINT SYS_C0011865 PRIMARY KEY (ID_LIVRO,ID_AUTOR)
);
CREATE UNIQUE INDEX SYS_C0011865 ON ADMIN.LIVRO_AUTOR (ID_LIVRO,ID_AUTOR);


-- ADMIN.LIVRO_AUTOR foreign keys

ALTER TABLE ADMIN.LIVRO_AUTOR ADD CONSTRAINT FK_ID_AUTOR FOREIGN KEY (ID_AUTOR) REFERENCES ADMIN.AUTOR(ID_AUTOR) ON DELETE CASCADE;
ALTER TABLE ADMIN.LIVRO_AUTOR ADD CONSTRAINT FK_ID_LIVRO FOREIGN KEY (ID_LIVRO) REFERENCES ADMIN.LIVRO(ID) ON DELETE CASCADE;